[project]
name = "japan-halal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "python-ulid>=3.0.0",
    "rich>=14.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
